<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-DT4EAKM" name="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest" tests="9" failures="0" timestamp="2020-05-12T22:36:19 COT" time="0.666" errors="2">
  <testcase name="testAddGame4" time="0.010" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest"/>
  <system-out/>
  <testcase name="testAddGame3" time="0.004" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest"/>
  <system-out/>
  <testcase name="testUpdateStory1" time="0.023" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at co.edu.icesi.internetcomputing.workshop.services.TsscStoryServiceImp.save(TsscStoryServiceImp.java:39)
at co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest.testUpdateStory1(TsscStoryServiceTest.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testUpdateStory1 -->
  <system-out/>
  <testcase name="testAddGame5" time="0.006" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest"/>
  <system-out/>
  <testcase name="testUpdateStory4" time="0.007" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest"/>
  <system-out/>
  <testcase name="testUpdateStory3" time="0.004" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest"/>
  <system-out/>
  <testcase name="testAddGame2" time="0.054" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest"/>
  <system-out/>
  <testcase name="testUpdateStory2" time="0.552" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest"/>
  <system-out/>
  <testcase name="testAddStory1" time="0.006" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at co.edu.icesi.internetcomputing.workshop.services.TsscStoryServiceImp.save(TsscStoryServiceImp.java:39)
at co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest.testAddStory1(TsscStoryServiceTest.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testAddStory1 -->
  <system-out/>
</testsuite> <!-- co.edu.icesi.internetcomputing.workshop.unit_tests.TsscStoryServiceTest -->
